version: "3.8"

services:
  riskopathic:
    build: .
    container_name: riskopathic
    ports:
      - "8080:8080"
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    networks:
      - graphnet
    restart: unless-stopped

networks:
  graphnet:
    external: true
    name: graphnet
